### ISSUE TITLE
一些小BUG

### ISSUE THREAD

**Issue by LeighSu** [gentaiscool/end2end-asr-pytorch#14]
1. 在librispeech数据处理的时候讲所有的字符处理成大写字母了
def _preprocess_transcript(phrase):
    return phrase.strip().upper()
但在data_loader.py读数据时将所有字符转成小写的了，但是transcript的数据有问题。
def parse_transcript(self, transcript_path):
        with open(transcript_path, 'r', encoding='utf8') as transcript_file:
            transcript = constant.SOS_CHAR + transcript_file.read().replace('\n', '').lower() + constant.EOS_CHAR

**Comment by LeighSu** [comment]
2. 在计算wer的方法中calculate_wer简单将word转成数字序号并转换为字符串，导致wer计算不正确，比如hello的id为12的话，会和id为1的hi和id为2的hei进行编辑距离计算。
建议使用editdistance模块的eval方法，直接支持任意类型的编辑距离计算。
https://github.com/aflc/editdistance

**Comment by SamuelCahyawijaya** [comment]
For number 2,`calculate_cer` and  `calculate_wer` accepts 2 string consist of characters instead of ids, the characters are generated from the following snippet which is executed before `calculate_cer()` and `calculate_wer()` are called inside the `trainer.py`
```                    
try: # handle case for CTC
    strs_gold = ["".join([id2label[int(x)] for x in gold]) for gold in gold_seq]
    strs_hyps = ["".join([id2label[int(x)] for x in hyp]) for hyp in hyp_seq]
except:
    logging.info("NaN predictions")
    continue
```

Please note that before calculating cer and wer, special characters such as SOS and EOS are removed, and for `calculate_cer()` all space characters are also removed
```
for j in range(len(strs_hyps)):
    strs_hyps[j] = strs_hyps[j].replace(constant.SOS_CHAR, '').replace(constant.EOS_CHAR, '')
    strs_gold[j] = strs_gold[j].replace(constant.SOS_CHAR, '').replace(constant.EOS_CHAR, '')
    cer = calculate_cer(strs_hyps[j].replace(' ', ''), strs_gold[j].replace(' ', ''))
    wer = calculate_wer(strs_hyps[j], strs_gold[j])
```
